# Generated by Django 5.2.3 on 2025-06-30 07:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCRBReport',
            fields=[
                ('report_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('score_online', models.IntegerField(null=True)),
                ('score_reason1', models.TextField(null=True)),
                ('score_reason2', models.TextField(null=True)),
                ('score_reason3', models.TextField(null=True)),
                ('gross_salary', models.FloatField(null=True)),
                ('fetching_date', models.DateTimeField(null=True)),
                ('decision', models.CharField(max_length=20, null=True)),
                ('dbr_percent', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100)),
                ('middle_name1_en', models.CharField(blank=True, max_length=100)),
                ('middle_name2_en', models.CharField(blank=True, max_length=100)),
                ('middle_name3_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=100)),
                ('first_name_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name1_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name2_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name3_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_ar', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('name_of_employer', models.CharField(blank=True, max_length=255)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('home_tel_number', models.CharField(blank=True, max_length=20)),
                ('work_tel_number', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('po_box', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_type', models.CharField(blank=True, max_length=50)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building_alpha', models.CharField(blank=True, max_length=100)),
                ('road_number', models.CharField(blank=True, max_length=20, null=True)),
                ('block_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry_date', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('login_attempts', models.IntegerField(default=0)),
                ('lockout_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BCRBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=100)),
                ('account_position', models.CharField(max_length=50)),
                ('payment_amount', models.FloatField(null=True)),
                ('payment_frequency', models.CharField(max_length=50)),
                ('finance_amount_or_credit_limit', models.FloatField(null=True)),
                ('outstanding_balance', models.FloatField(null=True)),
                ('relation_to_account', models.CharField(default='Owner', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbr.bcrbreport')),
            ],
        ),
        migrations.AddField(
            model_name='bcrbreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dbr.customer'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
