# Generated by Django 4.2.3 on 2025-06-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100)),
                ('middle_name1_en', models.CharField(blank=True, max_length=100)),
                ('middle_name2_en', models.CharField(blank=True, max_length=100)),
                ('middle_name3_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=100)),
                ('first_name_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name1_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name2_ar', models.CharField(blank=True, max_length=100)),
                ('middle_name3_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_ar', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('name_of_employer', models.CharField(blank=True, max_length=255)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('home_tel_number', models.CharField(blank=True, max_length=20)),
                ('work_tel_number', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('po_box', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_type', models.CharField(blank=True, max_length=50)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building_number', models.CharField(blank=True, max_length=20, null=True)),
                ('building_alpha', models.CharField(blank=True, max_length=100)),
                ('road_number', models.CharField(blank=True, max_length=20, null=True)),
                ('block_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('passport_expiry_date', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BCRBReport',
            fields=[
                ('report_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('score_online', models.IntegerField(null=True)),
                ('score_reason1', models.TextField(null=True)),
                ('score_reason2', models.TextField(null=True)),
                ('score_reason3', models.TextField(null=True)),
                ('gross_salary', models.FloatField(null=True)),
                ('fetching_date', models.DateTimeField(null=True)),
                ('decision', models.CharField(max_length=20, null=True)),
                ('dbr_percent', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dbr.user')),
            ],
        ),
        migrations.CreateModel(
            name='BCRBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=100)),
                ('account_position', models.CharField(max_length=50)),
                ('payment_amount', models.FloatField(null=True)),
                ('payment_frequency', models.CharField(max_length=50)),
                ('finance_amount_or_credit_limit', models.FloatField(null=True)),
                ('outstanding_balance', models.FloatField(null=True)),
                ('relation_to_account', models.CharField(default='Owner', max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbr.bcrbreport')),
            ],
        ),
    ]
