# Generated by Django 5.2.3 on 2025-06-30 07:57

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_user(apps, schema_editor):
    User = apps.get_model('dbr', 'CustomUser')
    User.objects.create(
        username='admin',
        password=make_password('nairdc123'),
        is_staff=True,
        is_superuser=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dbr', '0001_initial'),  # This dependency is now valid because the file exists!
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]